targets:
  $default:
    sources:
      - lib/features/**/domain/*.dart
      - lib/features/**/presentation/*_event.dart
      - lib/features/**/presentation/*_state.dart
      - lib/core/network/paginated.dart
      - lib/app/router.dart